/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_mainWindow (void);
GtkWidget* create_fileselection1 (void);
GtkWidget* create_general_settings_window (void);
GtkWidget* create_window_about (void);
GtkWidget* create_fileselection_cd_system (void);
GtkWidget* create_fileselection_cd_path (void);
GtkWidget* create_fileselection_rom_path (void);
GtkWidget* create_window_manual (void);
GtkWidget* create_window_input_settings (void);
