import os
import sys
import platform

Import("env")

main_sources = [
	'huku.c',
	'iniconfig.c',
	'lang.c',
	'miniunz.c',
	'unzip.c',
	'utils.c',
	'view_inf.c',
	'view_zp.c'
]

engine_sources = [
	'engine/bios.c',
	'engine/bp.c',
	'engine/cd.c',
	'engine/cheat.c',
	'engine/debug.c',
	'engine/dis.c',
	'engine/edit_ram.c',
	'engine/followop.c',
	'engine/format.c',
	'engine/gfx.c',
	'engine/h6280.c',
	'engine/hard_pce.c',
	'engine/hcd.c',
	'engine/list_rom.c',
	'engine/lsmp3.c',
	'engine/mix.c',
	'engine/ogglength.c',
	'engine/optable.c',
	'engine/pce.c',
	'engine/pcecd.c',
	'engine/sound.c',
	'engine/sprite.c',
	'engine/subs_eagle.c',
	'engine/trans_fx.c'
]

if env['PLATFORM'] in ('posix', 'linux', 'freebsd', 'darwin'):
	main_sources += [
		'osd_linux_cd.c',
		'osd_linux_sdl_music.c',
		'osd_haiku_sdl_machine.c',
		'osd_haiku_snd.c',
		'osd_keyboard.c',
		'osd_sdl_gfx.c'
	]
elif env['PLATFORM'] in ('haiku'):
	main_sources += [
		'osd_haiku_cd.c',
		'osd_haiku_snd.c',
		'osd_linux_sdl_music.c',
		'osd_haiku_sdl_machine.c',
		'osd_keyboard.c',
		'osd_sdl_gfx.c'
	]

program_sources = [
	main_sources +
	engine_sources
]

huku = env.Clone()
huku.ParseConfig('pkg-config --cflags --libs sdl')
huku.ParseConfig('pkg-config --cflags --libs SDL_mixer')
huku.Program(target = 'huku', source = program_sources)
