#!/bin/sh


if [ $1 == '--version' ]; then

  echo "1.3.0"
  exit
fi

PKG_CONFIG_PATH=/usr/i586-mingw32msvc/lib/pkgconfig pkg-config --define-variable=prefix=/usr/i586-mingw32msvc $@ gtk+-1.3-win32-production
